### ISSUE TITLE
[doc]No.10 什么叫「学会编程」？_v150911.0

### ISSUE THREAD

**Issue by KellyZhangQY** [OpenMindClub/Moment#12]
## 本次话题发起人：

 @haidao
## 参与者：

@岳建博 ，@矷佳 ，@高秋琪 ，@Dark@Helsinki ，@Emily 。
## 内容整理：

@矷佳
- 文案追踪: [OQWhatisCanCode · OpenMindClub/2.OMOOC.py Wiki](https://github.com/OpenMindClub/2.OMOOC.py/wiki/OQWhatisCanCode)
- 任务序列:
  - [x] 起草; 时间点?
  - [ ] 审核; 时间点? [「学会编程」是什么样的体验？ | 开智一刻](http://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=207901855&idx=1&sn=8eb2f535c11cd738cab92d30a4c3ff58&scene=1&srcid=0915cAOlOI5JTkqU7wc7mYjZ&key=dffc561732c226519a0d54afb5bbf900d252f15d53d466fa0656967661fdaaacc07b6bfaf77c08803cc2d72016d36f4f&ascene=0&uin=MTg1NDU4NTY4MQ%3D%3D&devicetype=iMac+MacBookPro8%2C2+OSX+OSX+10.10.5+build%2814F27%29&version=11020201&pass_ticket=JUlBxIXAbA8xBGmP2K3riOqIUjc6ACL%2FkPQ%2F75%2FGb2Mxhcg%2Brtv2Dw%2FRmGwUjAkv)
  - [ ] 发布; 时间点?
  - [ ] 反馈收集; 时间点?
  - [ ] 复盘改进

**Comment by ZoomQuiet** [comment]
[以 github 为核心的高效协同沟通](https://github.com/OpenMindClub/PRD/issues/1)

应该对应汇集为自个儿团队的内外信息流通规约!

**Comment by ZoomQuiet** [comment]
文案意见:
- 题图书中的 `C2-T2` -> `C2T2`
- "...不在win上" 统一 `win` -> `Windows` 专有名词话乱来

较多口语,应该由讲师来校对,俺全面修订就变成俺的回答了...
