### ISSUE TITLE
#INFO#  No.11 运动思维 与 编程思维 的相同点在哪里？_v150913.0

### ISSUE THREAD

**Issue by KellyZhangQY** [OpenMindClub/Moment#17]
## 话题发起人：

@萱小璧. ོYixuan 
Python 一期助教 + 班长。北京百里闪闪文化发展有限公司 创始人。
## 分享内容：

编程思维 = 会编程？
什么是…运动 与 编程思维 中的 道与术？
训练——如何从“臣妾做不到啊”到“让暴风来的更猛烈些吧！”

时间：9月13日 20:00-20:40

运动高手...编程高手... 都可以来。报名请戳  http://openmindclub.mikecrm.com/f.php?t=tSxWpy ，名额只有 5 个哦～

PS. 讨论结束发起者发「end 」后，其他群友可以再进行主题相关提问和分享。

**Comment by caosbad** [comment]
## 开智一刻后, 问答环节整理.

Q曹帅-北京: 班长威武，我想问的是，在编程思维中的演绎与归纳是如何被运用在运动中的呢？
A
1. 演绎 和 归纳, 简单的说就是 从 个别 到 一般, 和从 一般 到个别. 
2. 那么, 我刚刚讲的几个核心点, 就是 可以同时运用到 编程 和 运动 中的.
    \* 动作拆分 + 不断练习.
    \* 发现问题 → 明白原因 → 改善基础动作 → 解决问题.
    \* 了解 精神 + 肉体 可能会遇到的痛苦, 保证自己在遇到这类痛苦时不被打倒. 
    \* 提问的智慧 
    \* 任务量化.

Q弹壳er—廊坊:任务量化=复杂的事情简单做，跆拳道基本动作的习得=简单的事情重复做？

@曹帅-北京:@弹壳er—廊坊 大块任务拆解不等于简化任务，因为在你拆解任务的过程中，也会发现这个任务远比之前想象的复杂
弹壳er—廊坊 : @曹帅-北京 再次简化和拆解的区别？

曹帅-北京 : @弹壳er—廊坊 其实简化的是可执行或是可评估的意思

A@弹壳er—廊坊 是也乎, 又对又错. 
1. 核心是对的: 拆分任务后, 重复练习 基础动作. 
2. 然而任务量化, 是说, 
- 明白任务的边界: 主观 → 客观; 大型 → 阶段; 阶段 →小型; 小型 →可执行型....
- 明白自己能力的边界: 我到底能不能做到? 
- 任务检验标准: 怎样算做到了, 怎样算没有?

Q Frank Hu :我的问题是, 运动和编程学习中遇到不可避免的肉体和精神痛苦时, 班长是怎么对待的? 有没有经验可以分享给小伙伴们?

A:@Frank Hu 这个问题问的十分不错. 我上次在开智大群讨论过这个问题.   正好做了笔记, 发给你. 

#分享# 那天我们北京小组线下聚会, 我和 @才嘉 讨论到一个问题,
1. 我学了很多种 功夫, 武术、跆拳道、截拳道, 而且有的中间 可能隔了一两年, 就意味着, 我要把基础功从新学起.
2. 而我每次 放下功夫, 再从新锻炼的时候, 身体上是十分痛苦的. 因为, 可能筋拉不开, 可能体力需要从新提升.
3. 但我的内心是不痛苦的, 甚至说是愉悦的. 因为我的 “意识姿态” 曾经达到过那个地方.. 我知道这是一个必然的过程, 这个过程后 我的身体 会慢慢改善, 就不会再这么累, 不会高估 “当前痛苦”.
4. 刚刷开智正典里的一本书, 名叫 Matery, 里面有一句话:If our life is a good one, a life of mastery, most of it will be spent on the plateau.

> 我觉得一直强调 练习, 或者享受平台期, 没有什么意义. 真正有意义的在于, 研究为什么有的人会享受平台期. 我觉得, 想我上面描述的:
1. 过来人的心态.
2. 积极反馈.
   可能是 建立 这种心态的核心, 也就是说, 我经历过了, 我坚定的知道, 这种情况会过去. 同样的情况发生在 语言 学习中,
3. 当我经历了学习英语的 困窘, 说不出来话后… 我明白, 我只要克服交流时的这种困窘, 我就能学习会新的语言
4. 这种 自我反馈 + 过来人的经验(全局观), 可以帮助我 更享受 平台期, 也就可以 让我在 学习 第三种语言时, 速度加快.

曹帅：赞同，比如说第二编程语言的学习会在你熟练使用第一语言的状态下水到渠成。

Q对于一个没学过编程的人，这期Python班完成后对编程知识的内隐应该达到什么程度，然后有没有可推荐的知识列表可供参考？

@岑-成都 ［提问］对于一个没学过编程的人，这期Python班完成后对编程知识的内隐应该达到什么程度，然后有没有可推荐的知识列表可供参考？

答: 这次 Python 班, 主攻的是 编程之道, 而不是编程之术. 所以 Checklist 如下.
- [x] Markdown
- [x] Mailing-list
- [x] 学会 提问的智慧.
- [x] 量化任务. 
- [x] 学习的能力.
- [x] 科学上网, 抓取解决问题的信息的能力.
- [x] 与痛苦、焦虑相处的能力...
- [x] 做一个自己 Python 的项目…
- [x] so on..

Q在学习编程的时候，班长是先摸清整体知识轮廓系统的学习一遍还是走一步是一步用到什么去学习什么？

A@泰德-杭州 在学习编程的时候，班长是先摸清整体知识轮廓系统的学习一遍还是走一步是一步用到什么去学习什么？

答: 术 和 道 的问题, 你要摸清自己想要解决什么问题, 然后 基于这个问题, 系统的学习 知识轮廓.

@弹壳er—廊坊 第一编程语言呢？这时及时反馈的作用更重要了吧

答: 这就是我为什么没有直面 编程思维, 而是从运动思维 引出 编程思维. 所谓过来人的经验, 可以从自己的 其他 经验中, 借鉴过来. 主要可以借鉴的就是, 明白一点: 痛苦是有头的, 一切都会好起来的. 然后, 耐心的与痛苦相处, 就好了. 及时反馈是非常重要的... 这也是在课程中 需要学习的第一点. 
1. 提问的智慧: 如何正确的及时反馈?

Q@萱小璧. ོYixuan 继续提问班长，在运动中遇到不明原因的问题或是一直无法得到合理反馈时该如何应对？

A
1. 运动中, 就是 细化基础动作 → 清楚向教练描述自己的问题 → 按照方案 不断练习. 
2. 编程也是一个道理, 教练不可能忽然把一身 神功 几秒钟 B2B(Body to body, 噗) 的传递给你. 
3. 帮你识别问题 + 你的大量训练 = 解决问题的唯一途径...

ted :1. 运动中, 就是 细化基础动作 → 清楚向教练描述自己的问题 → 按照方案 不断练习. 
我想这也是爆栈网(stackoverflow)如此火爆的原因吧，有问题先拿问题去搜，实在没有就描述清楚了抛出来，利用集体的智慧

班长：大脑云端存储器. → 大脑分享的新纪元.

Q请问班长对自学编程或运动的小伙伴有什么建议？

A@曹帅-北京 自学编程 → 
1. 使用对的工具.
2. 找对的团体.
3. 正确的提问.
4. 基于 项目 大量的练习.

自学运动 → 
1. 自学 武术、散打、跆拳道、防强暴、打坐、击剑、保龄球? No… 还是找个教练吧. 
2. 减肥… 有需要找我私聊. 我有 无数个 纪录片 和 TED 给你看. 
3. 跑步: 买双好鞋, 开始跑.

caos :原来也是遵循最小的可行方案，赞一个

Q我想问个问题··   为什么班长精力这么旺盛  有什么秘诀吗

A:@邱瑄-武汉 有啊. 
1. 精力不旺盛: 一般就是, 没吃好, 没睡好, 想太多. 
2. 保持着 单身狗 的高贵身份.
3. 和 智商高 颜值高 的人呆在一起. 
4. 每天遛弯, 好好吃饭, 早早睡觉.

Q@萱小璧. ོYixuan 编程或者运动中反馈的例子？
A@弹壳er—廊坊 编程中的 反馈 就太简单了...你要的功能实现了没.
运动中: 比如我的 128 斤 到 98 斤, 比如马甲线、人鱼线, 比如 人变好看... 都是反馈呀. 
1. 跑步: 慢慢不累了.
2. 防强暴、武术、截拳道: 再也不被人揍了.
3. 保龄球: 它好好的往前走, 再也不出轨了...

Q身在职场，有时候被任务进度逼得不行。以运动类比的话，就是要达到一个超自己极限的成绩。是做还是不做呢，班长可有类似的经验分享一下？

A @泰德-杭州  身在职场，有时候被任务进度逼得不行。以运动类比的话，就是要达到一个超自己极限的成绩。是做还是不做呢，班长可有类似的经验分享一下？
1. 做. 
2. aim 在 100 分, 努力一下, 最起码 及格 也有 60 分. 
3. 比一开始就给自己定下 60 分要好.
4. 平坦和荆棘, 要毫不犹豫的选择荆棘呀...

**Comment by tedxt** [comment]
# 语音转文本
1. 好，那么正式开始我们今天的分享，我今天的分享分为两个部分。第一个部分是运动part，第二个部分是，主要通过之前分享的运动，然后让大家来了解一下编程思维到底是怎么一回事儿。现在开始我们的第一部分，大家看一下上面这个图。这个图叫做武术里面的一个动作，叫打扇子。是十分炫酷看起来非常帅的一个动作。但是呢要做出这个动作，其实他是要分步骤的，你首先要想要学会它，要把它拆成无数个基础的小动作。那么你可能要练成如何上步，如何摆手，如何下腰和如何屈膝。在所有基础动作熟悉之后呢再把他们连接到一起，反复练习就会出现上面这种神奇的效果图。
   ![351361169400892164](https://cloud.githubusercontent.com/assets/8284885/9843492/5476a27c-5aed-11e5-9668-c6fbb038af2a.jpg)
2. 那么好大家可能已经get到了运动当中的第一个点，也就是不论多么幸苦的动作。都是通过动作拆分和不断练习而习得的。那么在我学跆拳道的时候，有一个基础动作叫做踢脚把。然后呢，反馈的唯一的就是，证明你对不对的模式就是你把那个脚把如果踢了他一下，“啪！”一下，那就对了。如果踢的不响，那就是错了，就这么简单。我在一开始练习的过程中，怎么踢都踢不响。那教练就给我提出了两个原因，可能的两个原因：一、你的力量不够。二、你踢这个脚把的时候，你的脚面没有绷直。这时你不是以平面击打平面。那么得到这两个问题的时候，我不太明白。但是我可以，一个一个去验证，那怎么把它的力量踢够呢，就是提膝转胯抬（弹）腿。让每个基础动作都做对。
   ![115322177351923547](https://cloud.githubusercontent.com/assets/8284885/9843495/5f7fc018-5aed-11e5-9213-3d5ef1c3d881.jpg)
3. 二就是锻炼，每每一抬脚的时候，你不论击打任何一个物体。你的脚面必须是绷直的，而不是和你的小腿成九十度角。那第三个点就是我们可能听过什么叫做空手接白刃，这么一个神奇的武术家可能会有的一个动作，那他代表的是什么呢？它代表的是内隐记忆也就是我们又叫它程序记忆叫做implicit memory。嗯，内隐记忆呢，他是一个有什么效果呢，比如说我们简单的说我们会骑自行车、会游泳、会打字、会乐器，这些东西都称作内隐记忆。你一旦内化，然后它这个效果可以保持的十分的长久。比如说我会游泳之后十年不游泳了，十年之后我跳到一个坑里面我还是会游泳，这个就叫做内隐记忆。
4. 我们明白内隐记忆之后就会明白很多东西，一旦你习得就不会再忘记了。这个也是我们编程思维所具有的一大特性之一。那么在运动过程中，你肉体的痛苦都包括什么呢？上面这个图是我学击剑的时候，我为自己照下来的一张图，大家都觉得击剑穿着防护服所以你被抽到一下可能没什么关系。但是，大家可以看到我的手臂上一条非常红肿的印就是被剑给削到的，所以不论你学什么？他在肉体上都是有必然的痛苦。尤其你练武术的时候，你的身体素质对吧！可能跑个十圈二十圈，这是很经常的事情，然后你拉筋，有教练把你摁到地上，然后压着你坐老虎凳什么的，还有这种体能上。这些都是必然的痛苦。
   ![124920525508611649](https://cloud.githubusercontent.com/assets/8284885/9843499/67741ca6-5aed-11e5-8285-5aff540b6bdf.jpg)
5. 那么运动中精神上的痛苦包括什么呢？比如说我长跑的时候。我可能跑头一公里，我就会有一种哎呀臣妾做不到啊！就是。不断脑海里会不断有一个小人说放弃吧放弃吧放弃吧！还有学防强暴课的时候你穿上护具，然后简单的说就是在被教练揍吧。对吧？而且你不论是怎么练习你在很长一段时间里都是要被揍的。你就会自我怀疑为什么被揍的总是我，为什么我完全毫无还手之力？还有就是保龄球，我简单简简单单的拿着球站上轨道。把这个球扔出去，它为什么老是出轨，我是不是应该跟保龄球分手？这些都是你精神上的一个痛苦就是这个小人会不断不断的骚扰你。这个也是你在运动中和编程中都会遇到的问题。
6. 那么讲了半天之后编程到底和运动有什么关系呢？那我们把编程分为两个大的部分，第一个部分我们叫做术，他其实代表的是技能。什么叫技能啊？比如说，我们现在想要动手编一个东西么可能用Python可能用C，可能用C++可能用C#可能用java，这些都是技能。但是你唯一要跨过的点就是你要把那些基础的命令语句给搞明白，比如说variable（变量），然后怎么定义一个function?这些都是基础的，对应着比如说我们都对应着像跆拳道里面踢脚把，提膝转胯对吧，弹腿。
7. 当你不断的练习之后，这些数就会变成内隐，你再也不用想我要怎么打出一个句子？就是，到底是用print，还是用什么。这个术是你可以在不断的训练当中，给cover掉的。那么第二个变成了第二个点，也就是道，道到底是个什么东西呢？编程思维啊，简单的来说就是你解决问题的思维。解决问题的思维呢，目前两个很重要的一个是你提问的智慧，也就是说我遇到一个问题，我应该怎么去求救？那很多人一般就是遇到一个问题我立刻要一个反馈，这个就是一个错误的。正确的提问的智慧是，你能够清晰地描述你的问题，能够清晰地描述你为了解决这个问题所使用的方法。然后把这个发到正确的渠道，耐心的等待。
8. （接上）这个就是提问的智慧。那么还有一个就是除了编程员很少人有的一些思维叫做任务量化。什么叫任务量化呢？就是你能够把一个很大的问题，拆分成可执行，可以让人明白，我真的可以去解决的小问题。那第三个呢，就是我之前说的你对应的这个痛楚的点，当我尝试用编程去解决一个问题的时候，你会觉得哇好大的一个坑啊。其实这个代表的就是你精神上的痛苦和肉体上的痛苦。我不断的去努力努力努力，为什么就跳不过这个坑呢。但是你一旦在运动上经历过这个阶段你以后会发现，嗯不论怎样，事情总会变得更好，这个就是我的编程思维。

# 微信语音稿整理思路
1. 先把微信的语言转录出来，后面整理的时候需要暂停回退，这些都是微信语音没有的功能。
2. 利用微信的语音转文字功能，得到初稿。截屏得到图片。
3. 利用OCR软件将截屏转文字，去除多余的符号。
4. 结合之前的录音开始整理。done!

**Comment by YixuanFranco** [comment]
神速，到位。

**Comment by YixuanFranco** [comment]
## 我自己写的大纲, 可能有助于 整理吧...

Hi, 大家好. 我今天分享的主题是: 运动思维 与 编程思维 的相同点在哪里？？

先简单的介绍一下我自己....
##运动的合法代言人...
1. 南拳. - 4.5岁
2. 跆拳道. - 8岁
3. 各种武术....
4. 定向越野. - 13岁
5. 截拳道. - 15岁
6. 保龄球. - 19 岁
7. 击剑. - 20岁
8. 防强暴课程 R.A.D. Systems - 20岁
9. 一年健身 128斤 到 98斤. - 22岁
10. 高二打坐至今.
11. ....

我的 分享 分为两个部分:
1. 运动 Part.
- 从 小白 到 绝世高手?
  - 美丽的套路来自 动作拆分 + 不断练习.(打旋子)+  [旋子动作拆分](https://www.youtube.com/watch?v=x_MShI11Bxk) + 1 min.
  - 找到问题. (鲤鱼打挺、踢脚把) + 2 min.
  - 空手接白刃(内隐是什么). + 3 min.
- 运动的痛点在?
  - 肉体上的痛苦. (练素质、拉筋、击剑被削、体能) + 4 min.
  - 精神上的痛苦. (臣妾做不到...→ 长跑、为什么被揍的总是我、保龄球总是出轨我该跟它分手吗?)+ 5 min.
1. 编程 Part. 
   - 编程的相似点?
     - 术. (技能) + 6 min.
     - 道. (提问的智慧, 任务量化, 好大一个坑呀...) + 7 min.

---

1 min = 
- 没有 一夜成名 这种事儿. 台上一分钟, 必然对应着台下十分钟.
- 上面这个图, 是 武术 上的一个动作: 打旋子.
- 看上去这么炫酷的动作, 想要学会它, 首先要把它拆分成无数个 基础的小动作. 
- 你要单独的 练习, 如何上步, 如何摆手, 如何下腰, 如何屈膝, 
- 基础动作熟悉后, 在把他们连到一起, 反复练习, 就会出现如上图这般神奇的效果图.

2 min =
- 在我练习跆拳道的时候, 有一件事儿就是踢脚把, 

3 min =
- 内隐记忆（implicit memory）, 又称为程序记忆（procedural memory）
- 内隐记忆和宣告记忆是以不同的机制和不同的大脑回路来处理的。
- 程序记忆通常较不容易改变，但可以在不自觉的情况下自动行使，其可以只是单纯的反射动作，或是更复杂的一连串行为之组合。
- 程序记忆的例子包括学习骑 **脚踏车、打字、使用乐器或是游泳** 等。一旦内化，程序记忆是可以非常持久的。

4 min >
自由发挥...
