### ISSUE TITLE
#INFO# No.7翻转教学_v150909.0

### ISSUE THREAD

**Issue by badboy315** [OpenMindClub/Moment#2]
## 开智一刻 8 句话分享

参与者： 言夕、张晓芳、Rusel、Mingyi、达达

> 个人介绍

开智 Python 第一期零基础学员。 
- 做过两种 PM
- 偶尔也写豆瓣  ID： 弓和箭
### 【1】土鸡汤

![](http://img-storage.qiniudn.com/15-9-9/83689938.jpg)

> 序言： 今天分享的内容不是万精油， 也不是神丹妙药。 是 3.15 参加开智 PYthon 旗舰班之后的感受和自己经过的思考变化。 很多分享的道路和事实， 大家从来都不缺， 甚至说大家也通过某种渠道在一直知道这些信息。 就像大家上 MOOC 「哈佛幸福课」 一样， 道理很简单， 没有精巧的设计更没有一种谈奇。 有的是， 只是一个人在一种事情上面的个人感觉。 这段话主要是为了控制期望值。 接下来回到翻转教学？ 首先， 我想知道， 一般人所认为的翻转教学应该是什么？ 然后， 为什么需要翻转？ 最后， 不翻转和翻转的区别是什么？ 事实上， 分享的事情自始终都是围绕这么一些事情。
> 
> 互动环节， 三个小设问
### 【2】传统

![](http://img-storage.qiniudn.com/15-9-9/19584262.jpg)
- 翻转课堂 1min
  - 传统教
    - 讲解
    - 步骤
  - 传统学
    - 固定结果的反复练习

> 从小到大， 或许说， 包括现在。 传统的教学从来不会因为渠道的改变而随便改变。 小时候到大学有老师讲课， 会上网之后有 mooc， 工作之后还有带你的师傅。 从某种意义上面来说， 传统教学的意义和本质的趋同。 是追求某一种结果的单独目标。 在既定的道路， 让每个人走的更加有效率。 重点在讲授， 无论是当面， 网络， 言传， 都是讲授的媒体不同。 就算现在有了互联网， 并不能让我们学习变的更加有效率。 有 YC 创业课的第一课到最后一课的比例几乎就可以知道这点。
### 【3】真心不想翻

![](http://img-storage.qiniudn.com/15-9-9/9955655.jpg)
- 翻转的本质
  - 自身的出发点 
    - 寻找知识的本质 1min
    - 而非答案 1min

> 举例： Python 编程课的本质不是找答案， 而是拥有自己寻找答案的能力， 自证答案的能力， 可复用的能力， 会给「小黄鸭」讲故事
- 翻转的痛苦 1min
  - 自身拥有极大自主权
  - 当然， 自律也重要

> 正因为没有确定， 才是翻转的困难。 和高中到大学的相似在于看似的自由实际上是对人性最大的考验。 要不， 历史上也不会出一个曾国藩。 那么， 翻转的本意除了自己习得， 还有自我解释， 还能别人听懂。 那么， 这个可以参考的学习技巧「费曼技巧」。 除了之外， 如果让自己有主观能动性包括时间管理、 思维管理、 精力管理、 知识管理又是另外一个领域。 那么， 最小支点则是， 这件事情能做多久。 

![](http://img-storage.qiniudn.com/15-9-9/53824688.jpg)
- 翻转的结果
  - 思维的翻转
    - 姿势
    - 训练
    - 技法
    - 心法

> 翻转的结果， 其实很简单。 就是给自己造一个实验室。 在里面记录， 研究， 迭代， 不断记录， 不断研究。 除了这些基本的品质之外能达到之后， 再运用同济压力被动式的进步。 
#### 【4】翻来覆去

![](http://img-storage.qiniudn.com/15-9-9/85619255.jpg)
- 翻转的 TIPS
  - 自己就是一个实验场
    - 倒腾自己
    - 肌肉记忆
    - learning how to learn

> 关于翻转的技巧非常多。 可是「技法有限， 心法无限」。 所以， 最后， 只说心法。 打破自己的标签认知， 用行动迭代。

![](http://img-storage.qiniudn.com/15-9-9/41128166.jpg)
#### How

> 如何轻松自我翻转教学， 可以从自己想入手的任何领域。 重点在于可交付， 可输出， 作品。
- 写给自己的教程， 可复用
- 开源自己的作品， 参与

更进一步
- 同济
- 导师
- 线下
- 协同

**终极的翻转就是「拥有自我做主的能力」， 才是打开世界钥匙的开始。**  

---

作业：

参加的五位小伙伴设计自己的翻转教学任务

**Comment by rusell123** [comment]
## 互动环节

**弓与箭-深圳:** 
你会如何设计自己的翻转学习？

**言夕:** 
具体到某种技能，比如编程，初学者如何在完全看不到地图的情况下，自己去设计学习方案呢？

**rusel-常州：** 
在mook等平台上学习视频后，通行的做法是参与到讨论小组中，就相关问题一起探讨，然后通过脑图等方式将自己的学习思路共享出来，接受大家的一些建议。

**弓与箭-深圳:** 
现代网络肿么发达。学习地图这码事，好比思维导图。选择一个支点，可输出 …… 就好比，传统学习的时候，我们喜欢要课程表。可是事实上，课程表对于我们的价值是：信息！

那么，证明你习得编程能力的分解是什么呢？
- 知识点
- 爬虫
- web
- ... ...

然后每个知识点，你习得之后，是否可以复用给其他人用呢？

**弓与箭-深圳:** 
脑图++++

建议大家看 『learning how to learn』
脑图的信息结构，对于事后的整理有帮助，可是对于习得技能而言，不是高效的学习技巧。
- test yourself
- anki
- chunking
- recall 

这些都算是技巧。可是然并卵。

重要的是
- 如何 --- 逐步解决问题？
- 你会选择什么平台记录呢？ 
- 什么跟踪呢？ 
- 如何反馈呢？ 
- 如何证明学会， 而不是自我习得的假象呢？ 

**萱小璧：** 
[Learning how to learn](https://www.coursera.org/learn/learning-how-to-learn/home/welcome)

**萱小璧：** 
Coursera课程。

**rusel-常州：** 
感觉@弓和箭-深圳 今天主要讲的是个人的翻转学习，而大家平时了解的可能更多是学校里的翻转教学。这样是不是就会有个问题，个人的学习成果与他人分享，是否就能得到比较有指导意义的反馈。因为不同的学习平台有不同的参与人员，可能未必有资深一些的人士来交流。而传统课堂中的老师毕竟是属于引导人的性质。 希望@弓和箭-深圳 能和我们分享下你的看法。

**325-北京：** 
如何证明学会的确是个问题，这样子的情况下会去参照已成型的案例，相对比，看缺失那块，重点是思维方式的差异，是否解决问题。

**弓与箭-深圳：** 
学校？！ 超过控制范围哪！
我们试图转换一下『如何大批量进行翻转教学』， 例如针对「培训班」「员工培训」 …… 等等。

**弓与箭-深圳：** 
翻转教学的设计之一，不是过程的辅导导向。
- task，学员通过自己的力量去寻找 

**弓与箭-深圳：** 
其次， 完整的翻转教学， 不是完全这一次可以谈全的哪。
其实群里有许多一期掉队的学员可以站出来谈谈，或者写作班的学员。最大的问题，是自律！自我跟踪！持续增补！

**simon-湖州：** 
我觉得学习的方法、过程等就是殊途同归，每个人的切入点不一样。而我学习一样技能也好，知识也好，就先找该领域中的分享资料。包括论坛帖子、博客文章、视频。通常只有牛人愿意分享的情况下，才变的高效。

**325-北京：** 
通过自己的力量去寻找，的确是翻转的本质，知识点的输入因个体的差异化而不同，如google的工程师创建的Altschool，就是很好的例子，通过技术实现个体差异化的学习。

**裘德-南京：** 
写博客也算教自己的方法一种。

**达达-上海：** 
写博客更多算是记录吧。

**弓与箭-深圳：** 
yes.
- 能表达出来，并且别人也能听懂。就是「小黄鸭」技巧。

更多的翻转，在群体的智慧里面还可以
- github 
- gitbook 
- 协同
-  …… 

**Mingyi-上海：** 
如何证明自己学会一个东西？能够把学会的东西讲述给别人也算是一种检验的方式，而写博客就是这种途径之一吧。

**弓与箭-深圳：** 
嗯。 当然算 …… 途径之一》

隐喻和类比。

如果你写一本书出来，获得业内认同，so ^ . ^

这个道理都明白，问题是如何 how. 

就是复杂的变量设计的问题了？
- 克服心理上，情绪上
- 生活上，工作上
- 每一个里程碑
- ……

**325-北京：** 
这件事对自己有多重要，为什么要做，可以舍弃什么？

**Mingyi-上海：** 
写书或者类似的举动是需要长时间的积累和投入，而多数时候人对反馈的要求是那么的快，所以，需要自律和坚持。

**325-北京：** 
习惯成自然就习惯了，有时候还割舍不掉。比如健身，本质上多巴胺分泌带来的快乐感实际上在投入做事情产生的flow是一样一样的。

**弓与箭-深圳：** 
yes.

不用说，长时间。就是短时间，类似三个月的都不容易做到。减肥很简单，每天跑就可以。喊几个人试试。
所以说，其实，道理都简单，做到不容易。

先解决心理问题， 才是技术问题。 如何用工具在相同时间走的更快。也就是翻转的难点。是『心理』而非技术。 

**Mingyi-上海：** 
如何用工具在相同时间走的更快。也就是翻转的难点。这个难点现在有什么可以分享的吗？

**325-北京：** 
把大/长目标拆分成小目标，每一个小目标具体到可以找到已经成型的案例对照，即时反馈，更正。

**rusel-常州：** 
这的确更多是需要养成一个习惯去贯彻，所以即时的反馈也能给学习者带来心理上持续的满足感，使其能一步一步前进。

**弓与箭-深圳：** 
…… 切入点就是『坚持』。
- 社群
- 导师
- 里程碑管理
- 同济

都是可以帮助持续下去的因素之一 。

**325-北京：** 
传统的教学最大的问题就是反馈不及时，所以学生的好奇心与求知欲慢慢的就没了。

**dreamu：** 
对要学的点拆分，在学的过程中不断自证学会，stay focus之后具体的方法论自己去寻找，比如费曼技巧，小黄鸭技巧，或者博客等等。目标定好，寻找路径，最有益的在自己寻找方法论上，个人能动性发挥出来。

**弓与箭-深圳：** 
嗯，不是问题，是现状。 
- 不过学生的内在动机也不够，也是问题之一。 

**言夕：** 
怎么知道要在某个特定阶段去什么地方找有助于自己成长的反馈呢，虽然有强大程序员问答社区和前人的资料，但某些时刻确实有些力不从心；
某些问题是可以通过反复迭代来解决，但有时没有在特定的问题上得到反馈，可能就掉队了。

**刘昌坤-苏州：** 
在动机不够怎么处理？不断的给自己画饼么？自我激励怎么才能更有效地驱动自己。

**弓与箭-深圳：** 
这个问题重复了。上面已经说了哪@言夕-北京。

**弓与箭-深圳：** 
好，最后一个问题。

画饼能画多久哪。自我激励能做到多久呢！
要不，中国就有好多曾国藩了。

简单来说，牛人不需要自我激励。因为知道要去哪里。普通人，最有效的办法， 就是加入 改变环境，影响自己。 

**刘昌坤-苏州：** 
就是换个环境吗？

**325-北京：** 
所以学会的过程实际上就是不断的完善最初的成品吗？寻求帮助，翻看案例，讨论检验？如果友情分享的话，弓和箭是否可以分享自己最有成效的学习路径？谢谢。

**弓与箭-深圳：** 
End.

今天的翻转教学，只是一个开头。

这个话题，俺们可以持续的说。针对你自己想学的领域，如何设计自己的翻转教学？
- 可以记录自己的心路历程
  - 认知教学
- 可以里程碑学习
  - 可复用技巧
- 所谓的乱七八糟的各种管理技巧
  - 时间、精力、思维、知识
- 如何识别有用的人帮你
  - 识别和试错也是技巧哪
- 写不完了，其实这些都可以是你自己的翻转啊

那么，你的翻转是什么呢？

END.

**Comment by rusell123** [comment]
## 自由讨论

**Moie：** 
我想问个问题，怎么将复杂的问题简单化？除了不断的拆分之外，还有什么好的方法？另外就是将一个简单的问题复杂化，更深入的理解它？

**弓与箭-深圳：** 
翻转的本质， 是不断解决问题的过程。锻炼自我解决问题的能力才是最关键的，而不是可复用环境。

还是以『减肥』为例。试试，能不能知行合一的完成呢？
- 方法
- 意志力
- 试错
- 调整
- 自我反馈
- 自我激励
- 时间安排
- 分享

减肥 ，一件十分简单的事情。so ^.^ 能说的事情太多了。所以，我想说。方法和技术不是关键。 

设计教学和按照教学计划执行，调整和反馈，灵活处理。解决问题的能力才是关键的哪。

**325-北京：** 
解决问题——带着这个强硬的目的去做，是最佳的压力与衡量标准，赞一个。

**rusel-常州：** 
自我意志力和自我暗示我觉得《习惯的力量》这本书讲得更有操作性一些。翻转学习的自主设计学习反馈就是可以让个体学习习惯得以科学化。

**325-北京：** 
最近在看志平老师推荐的《机器人叛乱》，理性的光辉照耀在习惯上抵抗基因的自私，也是在争取自我效率与利益的实现。

**弓与箭-深圳：** 
嗯哪。5位参与者可以试图设计一个想要学习的翻转教学。并跟踪自己的计划， 反馈 ……可以完美的异步沟通中， 用行动去体会哪。稍后建立 github issue , 所有需要沟通的朋友， 可以异步沟通。也可以看 5位参与者自己的翻转尝试。

**Comment by badboy315** [comment]
嗯。 
距离分享已经过去了 16 小时。
除了有两个纪要之外， 木有看到分享之后

+ 看法， 观点， 想法
+ 翻转教学的设计

**Comment by badboy315** [comment]
分享之后已经过去 17 小时
只有纪要， 木有看到 5位参与者自己的
- 思考
- 输出和可交付行计划
- 自个的翻转方案
- ……

翻转， 教学的最大点不是技术。 而是先 内心 坚定， 才是 工具技术。

继续等待中 ……

关于 [输出和可交付， 见之前的聊天记录](https://github.com/OpenMindClub/PRD/issues/13)

**Comment by KellyZhangQY** [comment]
说一说我昨晚的感受：

> 翻转课堂，其实就是如何通过各种方式给自己造一艘船，你是用人手造还是机器造，这些都是工具技术的一部分

其实关键还在于你想造这艘船的决心有多大，并交付计划和结果；例如：
- 持续学习的计划
  - 如何实施（你准备投入的时间和精力为多少）
  - 适合你的最优途径是什么？（在线教育、自我学习、结队学习、模仿大牛学习路径）
  - 有哪些捷径？（例如学习英语，好的网址有哪些，好的书籍又有哪些？）
- 过程中遇到的难点是什么？如何解决？
- 交付的结果如何？
- 周期性总结反馈计划阶段性的成果，并不断迭代计划

翻转课堂，往大了说大家可能都会觉得是上课的形式，其实我觉得翻转课堂，其实是翻转自我，不断挑战提升自己
