### ISSUE TITLE
#INFO# No. 5 如何通过避免发错音说一口漂亮的英语_v150915.0

### ISSUE THREAD

**Issue by KellyZhangQY** [OpenMindClub/Moment#8]
如果你恰巧没赶上开智青年群内的这次讨论，没关系，欢迎继续在这里进行异步沟通——
本文档可以多人同时编辑，移动端打开点击你想增补发言的位置就可以直接修改，欢迎你继续发表看法哟，在网页版打开还可以直接标注任何你想评论的内容~

p
本次话题发起人：@班长
参与者：@蝈蝈、@佳怡、@迪卡斯、@四毛、@糖糖
内容整理：@蝈蝈
## 活动预告

『开智一刻』No.5  如何通过避免发错音说一口漂亮的英语。

说普通话还常常发音不标准，何况第二外语；说英语时常常不自觉发错音导致各种尴尬和不自在？今晚，班长与您分享：如何通过避免发错音说一口漂亮的英语。

分享者：李熠瑄（群里大家都亲切得叫她班长）北京人. 练过武术，学过python； 悠悠鸟字幕组校对, 翻译 + 校对了几十部电影. 但不喜欢看任何电影, 包括自己翻译的. 喜欢音乐、读书(哲学 + 霸道总裁文)和到处走走.

时间：9月6日21:00-21:30

欢迎爱英语爱班长的小伙伴参加讨论！

期待5位线上主要参与者最好有倒腾过如何学英语，锻炼自己口音的经历，如果能分享你学习过程中不为人知的特别小技巧以及这个过程带给自己的改变最好不过啦！语音过后，大家可以自由提问，方向不限。期间班长会穿插图片作为辅助材料。也欢迎5位主要参与者准备一下关于自己相关图片，影音等资料。

感兴趣的小伙伴戳表单报名参与，http://openmindclub.mikecrm.com/f.php?t=CcjFA6 ，名额只有5个哟。
## 内容整理：

缘起：

分享一个东西, 以前不是分享过一个 英文学习方法 吗, Part 3 中的 意群这个概念, 当初一笔带过了, 没仔细的说:
1. [意群](http://baike.baidu.com/view/1679579.htm): 意群就是指句子中按意思和结构划分出的各个成分，每一个成分即称为一个意群。同一意群中的词与词的关系紧密相关，密不可分，否则就会引起误解。
2. 前阵子 听阳老说了 自主心智 和 算法心智后, 整理了一下思路.
3. 比如, 你背单词, 就是 明白了 模块1, 模块2, 模块3, 某种语法就是 规则1, 规则 2, 规则三. 而你表达一样东西, 可能需要: (模块1 + 模块2)\* 规则1 + 模块三\* 规则2. 那么, 你要表达一个意思, 就会非常的痛苦. 也会非常的缓慢.
4. 那么, 建立一个意群: 意群1 = 模块1 + 模块2)\* 规则1 + 模块三\* 规则2, 也就是说, 你下次就直接调用这个 意群1. 速度就会大大加快.
5. 这就是, 为什么 你背了一堆单词, 然而开口还是说不出来话的 一大原因 吧.

总之就是, 减少大脑 需要处理的 模块 和 法则, 举例来说:
1. 比如我前两天, 在朋友圈发了一个大碗, 写 "Chill the fuck out, I got this." 如果拆分模块 来理解, 可能以为我在骂人.
2. 但其实不是那个意思, 这句话是一个整体, 可以理解为, "淡定淡定, 我来搞定…" or "你 XXX 给我放轻松, 放着我来" 之类的 "感觉. "
3. 如果你理解了这个模块, 在 阅读 或 口语时, 理解了整个意群, 而不是 再去处理模块, 那就会简单很多啦.

---
## Sept.6, 2015

---------害羞的分割线-------------
1. 美音为主, 大不列颠众友莫喷. 我发誓这次讲的东西学完你们立刻就能用上, 多加练习肯定没问题.
2. 水平有限. 分享为主...但我保证言之有物. 主要讲明白中国人发不对的口音, 如果你有印度腔, 咱们可以讨论. 也可以帮你找出来.
3. You can speak English that is clear, but accented. 这次分享的目的是, 帮助大家把话说清楚, 说明白. 而不是变成 ABC.
4. 语音数量有限, T_T 我要谨慎使用. 所以, 会搭配一些文字, 讲解. 让大家更容易明白发音的规律.
5. 我分享完后, 会把文字稿发给大家.(所以不用一遍听一遍抄笔记...我也是想太多)

-------------打板线----------------
语音分为三个大部分. [图]
1. 基础音纠正: consonant + vowels
2. 节奏 和 调子到底是什么 Stress, Rhythm, Intonation.
3. Loudness, Speed, and Phrasing.
1. 基础的错误.[图]
   - 傻傻分不清党【V1】
     - hit/I/ --- heat/i/ 重点: 音标, /I/ 发"耶, /i/ 发"咦.(shit, sheep)
     - mad, apple /æ/ --- get/e/ ---may/eI/
     - too/tu:/ -- good-book/ɡʊd/
     - th(think - they)-z(zoo) 咬舌.
     - I love you. w-v five
   - 嘴要厥出来党【2】
     - 句首的 R(rock n roll), W-V. 我们. - what the hell.
   - 没有存在感的错误
     - 句中的L. - world 不等于word.
       只要单词内部有L，就要发出来。
       > 比如world发成wor哦d。
       只要单词首字母是w和R就要记得把嘴撅出来。
       >  Create，这个中间有R，嘴也要撅出来
     - better - bedder, hot - ha,t, love.
     - down - town.
     - pain - pay nine - (ni)
     - 常见吞音 - commitment = com mi ment
   - 结尾的 s,【3】
     - t, f, k → s hopes
     - d, v, g → z  ex: loves = lovez,
     - x, ch, se, /IZ/ /əZ/ → nurses = nurse is. pages = page is.
   - 结尾的 ed【4】
     - d -t ,needed = need id, Get started = Star day-d
     - voiced = n, v, moved, plan + d
     - voiceless = picked,missed + t
   1. 语调.
      1. 句子: 你今天吃饭了吗. - XX。 - XX。【5-6】
            com-PU-ter → We KNEW her.
   2. 短语: Give up → gi - vup
          Stop it → sto - pit
          Check in → Che - kin
          Drop it off → dro - pi -toff
          Gets up → get sup
          send her → sender...
          Him, Let him go.
   3. 单词[Word Power Made Easy](http://book.douban.com/subject/1756614/)【6-7】
      - suc. CESS. ful
      - ca.REER
      - FORty fourTEEN, EIGHty-eighTEEN
      - 90% 双音节 名词, 重音在第一个: COUNtry, DOCtor, PENcil
      - 60% 双音节 动词, 重音在第二个上: enJOY, subTRACT.
      ---
      
      Material
      1. 一个非常有意思的语言项目
      
      > 两个加拿大人 Scott Young 和 Vat Jaiswal 花了一年的时间旅行了几个国家，途中坚持不说英语，他們分別在西班牙、巴西、韓国与中国各待了三個月，学习当地的文化及语言，最后他们学会了四学习西班牙语、葡萄牙语、韩语以及中文。
      > 推荐大家 看在中国的三个月 的视频版本. 看完会很震撼. 原来语言真的可以学的这么快的.
      > - [The Year Without English文字版本](http://www.scotthyoung.com/blog/myprojects/the-year-without-english-2/)
      > - [简短视频版本](http://v.youku.com/v_show/id_XOTExNDIwMzM2.html?from=s1.8-1-1.2)
      > - [在中国的三个月-视频版本](http://v.youku.com/v_show/id_XNzI0MDAyMDQw.html)
      1.  [WELL SAID](http://www.amazon.com/gp/product/1413005101/ref=pd_lpo_sbs_dp_ss_1?pf_rd_p=1944687742&pf_rd_s=lpo-top-stripe-1&pf_rd_t=201&pf_rd_i=1424006252&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=0QKCRTPR4T7XRS9QSBSR)
         > International Student Edition by **Linda Grant**. 要买红色的, 别的颜色的都不对. 不知道为什么这本书这么贵...大家各显神通的买吧...

----------------萌萌的讨论线-------------------
## 问题解答
1. 【蝈蝈】问：美语卷舌音要怎么发才好听？很多人发不好。
   【班长】答：把舌头顶住前门牙, 发ziiiii 的声音, 然后慢慢把舌头, 往上膛的方向收。如果发不出来, 那就统一发 e, 没什么问题。
   2.【四毛】问：有的时候照着学了，但又不自信，不知道自己学对了没，该怎么办呢？是否有工具可以帮助自己检查发音呢？
   【班长】答：听他读, 模仿, 录下来, 对比, 标出不对的地方, 再读。
   3、【大树】问：想找一个人能坚持学习口语的方式。
   【班长】答：没有语言环境是难。推荐《单词社交网络》，不过不适合入门。初学者可看Bingo教你学美语。[在中国的三个月-视频版本](http://v.youku.com/v_show/id_XNzI0MDAyMDQw.html) 这个视频，一定要看。
   【mew】答：如果外国人听不懂的话一般他们会重复一遍，这个时候赶紧记下来。
   4、【四毛】问：班长是否考虑开个公众号，每天纠正一个音，订阅者学习时也直接借助微信录音对比。
   【班长】答：其实这个 Bingo 和很多人都在做啊. 关键是要按照秘笈去练，或者天天叨叨叨, 有人给纠正, 就很快。
   5、【大猫】问：学英语最难的是啥？缺乏语言环境？坚持不下来？
   【班长】：就是用。比如我 谈恋爱, 会有一个域, 叫A域, 那么我很快就能学会这个领域. 比如我要做 CS 的Pre ，有 B 领域的单词就能讲明白, 那我就只想学 B.
   6、【holt】问：请问一下班长有看过奶爸的《把你的英语用起来吗》？那里边推荐的是跟赖世雄学口语，主张透析法读英文原著。
   【班长】答：@holt 我有那本书, 但是没看，那本书更像资料索引大全， 没看过赖世雄的,。刚分享的, 主要来自《well said》+ 一个美国人的教导+我个人的感悟。弄一个 “你也不知道是什么但是很好用的软件” 然后去 youtube 找一些你喜欢看的东西, 这样比较好玩。
## 自由讨论
- 关于重音
  
  > 【flyink】判断重音的法则：音节在两个及以上的单词，重音一般在倒数第二个音节。如important, recognition, foundation, comitment. 等等
  > 【yixuan】tion, tic,这种, 比如, recogNItion, founDAtion, 基本重音都重在 tion 前面那个音节.
- 关于口音
  
  > 【糖糖糖】如果只是想走世界，口音纯正并不是必须的，常用词的词汇储备，让人听得懂的发音程度，生动的肢体语言，脸皮厚。

> 【班长】口音不是要命的事儿, 但我开始注重口音, 是因为, 我发现一个英文单词我会念了, 我就记下来了. 但是, 抄拼写的记不下来, 于是就开始抠语音, 觉得反正都耗时间了, 不如说的好一点. 然后就慢慢的较真儿了.
- 关于读外文书
  
  > 【糖糖糖】：我读的英语专业书多，就进化成只有读专业书时才效率速度快的奇形种，反而读通俗小说时经常抓不住points。
  > 【班长】我读本专业 的书 和 英文的霸道总裁文 就特别快, 但比如瓦尔登湖，查词从头查到尾。建议大家从英文小艳本开始看, 或者小的总裁文。不用为了读有意义的书而读有意义的书，让自己快乐快乐才是意义. 用自己喜欢的东西当资源最好了。建议没有被墙的小伙伴，直接在 play store or apple store里找英文小说。
  > 【曼殊】直接读原著，被虐一两本书，踏过心理障碍坎，习惯了就好。
  > 【钰玲】根據自己喜好讀是最易堅持的方法。
  > 【holt】根据兴趣看的书速度都不一样。
- 七嘴八舌
  
  > 【大猫】说或写比听和读复杂很多，因为同时处理两件事情：英语+内容。口语也应该跟写作一样事先准备，要跟别人讲的日常口语也可以自己先写个剧本，先预演起来。
  > 推荐《英语口语红宝书》口语教材，解决二外口语中的两个问题：在不同场合下正式，非正式口语如何选择；表达同一种意思的多种方式。使用方法：无需通读，每次交流前根据情景，目的，从书里找内容预习并收录进自己口语常用手册。
- >【ziyan】thirty fifty 这种以十为计的 “ty” 里面都发“d”不发 “t”。
## 关于口语学习的总结
1. 注意音标. 
2. 听发音. 
3. 一定要模仿, 一定要念出来. 慢则半年吧. 基本一张嘴就能发正确的音了. 每天念十个词...

**Comment by YixuanFranco** [comment]
Super!
